version: '3'
services:
  server:
    build: ./chihaya
    restart: 'unless-stopped'
    volumes:
      - './chihaya/config:/etc'
      - './Tcpdumps:/tcpdump'
    ports:
      - '6880:6880'
      - '6880:6880/udp'
      - '6969:6969'
      - '6969:6969/udp'

  client:
    build: ./Transmission
    restart: 'unless-stopped'
    volumes:
      - './client/config:/transmission/config'
      - './client/torrents:/transmission/downloads'
      - './client/watch:/transmission/watch'
      - './Tcpdumps:/tcpdump'
    ports:
      - '9091:9091'
      - '9095:51413'
      - '9095:51413/udp'

  client_2:
    build: ./Transmission
    restart: 'unless-stopped'
    volumes:
      - './client_2/config:/transmission/config'
      - './client_2/torrents:/transmission/downloads'
      - './client_2/watch:/transmission/watch'
      - './Tcpdumps:/tcpdump'
    ports:
      - '9098:9091'
      - '9099:51413'
      - '9099:51413/udp'
